Merge the upstream and fix mm.rs to work with.
kaist-cp/hafnium-verification pull request #3
Opened 2019-07-16 11:13 UTC by efenniht

- #2 를 해결.
 - Upstream (https://hafnium.googlesource.com/hafnium/) 과 머지.
 - Upstream의 `src/mm.c` 코드의 수정에 대응하는 Rust 코드를 수정.

2019-07-16 12:55 UTC, jeehoonkang commented on hfo2/src/mm.rs
> +pub struct mm_stage1_locked {
`mm_stage1_locked`는 public interface에 드러나는 타입이므로, 만들긴 해야하는데..

- `ptable: usize`로 두고 (타입을 지정하지 않겠다는 의미),
- `HYPERVISOR_PAGE_TABLE.lock()` 한걸 usize로 cast해서 들고있으면 어떨까 합니다.

위와 같이 하면 따로 RawSpinLock을 둘 필요 없이 `mm_stage1_locked`를 구현할 수 있고, 또한 이게 좀더 원래 코드의 의도에 충실한 구현이라 생각합니다.

2019-07-17 03:56 UTC, efenniht commented on hfo2/src/mm.rs
> +pub struct mm_stage1_locked {
원래 코드의 구현에 충실하려면, `mm.c` 의 `mm_defrag`, `mm_identity_map`, `mm_unmap` 함수들이 따로 락을 걸지 않으므로 아예 `HYPERVISOR_PAGE_TABLE` 의 SpinLock을 없애고 h6a19a4fade4087d61944d28adc4c889b82ffe2ca 이 커밋처럼 락을 분리해 두는 게 더 좋을 것 같습니다.

2019-07-17 07:27 UTC, jeehoonkang commented on hfo2/src/mm.rs
> +pub struct mm_stage1_locked {
저는 위 댓글에서 제가 말씀드린 방법을 여전히 더 선호하는데, 그 까닭은:

- RawSpinLock을 안쓰고 SpinLock을 쓰는게 좋을 것 같습니다.  왜냐하면 RawSpinLock은 어떤 data를 protect하는지에 대한 정보가 전혀 없기 때문입니다.  
- 위에서 제가 언급한 방법이 원래 코드의 의도를 더 충실히 반영한다고 생각합니다.  `*_locked`의 의미는 무엇인가 락을 걸었다는 소유권을 나타내고, 이를 Rust에서 가장 온전히 표현하는 방법은 `*_locked`를 `SpinLockGuard`에 매핑시키는 것입니다.

2019-07-18 05:39 UTC, efenniht commented
- `mm_stage1_locked` 의 `Deref` 와 `DerefMut`을 구현하여, 작동을 확인했습니다.
 - Submodules 중 업데이트해야 하는 것들을 업데이트했습니다.

2019-07-18 06:16 UTC, jeehoonkang requested changes

2019-07-18 06:16 UTC, jeehoonkang commented on hfo2/src/mm.rs
> +static mut HYPERVISOR_PAGE_TABLE: SpinLock<PageTable<Stage1>> =
그냥 static으로 해도 되지 않나?

2019-07-18 06:16 UTC, jeehoonkang commented on hfo2/src/mm.rs
> +/// Locked hypervisor page table
주석으로.. 되도록 나중에 지우기를..

2019-07-18 06:16 UTC, jeehoonkang commented on hfo2/src/mm.rs
> +    ptable: usize,
`usize`가 실제로 의미하는게 뭔지 간단히 주석

2019-07-18 06:16 UTC, jeehoonkang commented on hfo2/src/mm.rs
> +            lock.get_mut_unchecked()
`get_unchecked()`?

2019-07-18 06:16 UTC, jeehoonkang commented on hfo2/src/spinlock.rs
> +    pub lock: RawSpinLock,
no pub

2019-07-18 06:51 UTC, efenniht commented
@jeehoonkang 지적하신 사항을 모두 고쳤습니다!

2019-07-18 06:54 UTC, merged